### ISSUE TITLE
Search Box throws UnboundLocalError

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#495]
The search box in the upper right part of the screen is broken. It seems to be broken for anything you select.
 
**UnboundLocalError**
UnboundLocalError: local variable 'resp' referenced before assignment
 
Traceback (most recent call last)
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
response = self.get_response(request)
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 128, in get_response
response = self._middleware_chain(request)
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 49, in inner
response = response_for_exception(request, exc)
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 103, in response_for_exception
response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 138, in handle_uncaught_exception
return debug.technical_500_response(request, *exc_info)
File "/usr/local/lib/python3.8/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
raise exc_value.with_traceback(tb)
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
return func(*args, **kwds)
File "/app/roundabout/search/views.py", line 86, in searchbar_redirect
return resp
UnboundLocalError: local variable 'resp' referenced before assignment

Release 1.7.0, Pull request incorporated on 12/14/21.

**Comment by sbatchelder** [comment]
Ah I see this happens when the search field is blank. I had failed to check this after the #487 fix. Good catch, thanks.

**Comment by joannekoch** [comment]
This is fixed.
