### ISSUE TITLE
Calibration Edit "Permission Denied" error.

### ISSUE THREAD

**Issue by sbatchelder** [WHOIGit/ooicgsn-roundabout#81]
When I click "edit coefficients" on an Inventory/instument with calibrations, nothing happens. 
![image](https://user-images.githubusercontent.com/44208509/83413924-9d99d280-a3ea-11ea-8fda-536330da6588.png)

The django console output shows the following PermissionDenied error.
```
Forbidden (Permission denied): /calibrations/ajax/edit/6/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 84, in dispatch
    return self.handle_no_permission()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 43, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
```
The user I was doing this as is registered as admin
![image](https://user-images.githubusercontent.com/44208509/83414057-d76ad900-a3ea-11ea-9555-bd57adca87ec.png)

**Comment by MarioCarloni** [comment]
Permission issue has been resolved for Calibrations, as well as Configs/Constants, by updating the object reference in the permission_required attribute for each view.
